stages:
  data_ingestion:
    cmd: python src/data_ingestion.py #command to run
    deps:
      - src/data_ingestion.py #dependencies location
    outs:
      - data/raw #where the output will be stored

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw
    outs:
      - data/processed
  
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed
    outs:
      - data/features

  model_building:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/features
    outs:
      - model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
        - model.pkl
        - src/model_evaluation.py
    metrics:
        - metrics.json